data:
  raw_data_path: "notebooks/data/diabetic_data.csv"
  db_path: "artifacts/readmission_data.db"
  train_data_path: "artifacts/train.csv"
  test_data_path: "artifacts/test.csv"
  test_size: 0.2
  random_state: 42

model:
  target_column: "readmitted_binary"
  model_path: "artifacts/model.pkl"
  preprocessor_path: "artifacts/preprocessor.pkl"